/* * DATA ZONA GEMPA BUMI (Tabel III.D)
 * Struktur: Provinsi -> Kota/Kabupaten -> Zona (1-5)
 * Sumber: Lampiran III - SEOJK No 6/SEOJK.05/2017
 */

const zonaGempaData = {
    "BALI": {
        "KAB. BADUNG": "4",
        "KAB. BANGLI": "3",
        "KAB. BULELENG": "3",
        "KAB. GIANYAR": "4",
        "KAB. JEMBRANA": "3",
        "KAB. KLUNGKUNG": "3",
        "KAB. TABANAN": "3",
        "KOTA DENPASAR": "4",
        "KAB. KARANG ASEM": "3"
    },
    "BANTEN": {
        "KAB. LEBAK": "4",
        "KAB. SERANG": "4",
        "KAB. TANGERANG": "4",
        "KOTA CILEGON": "4",
        "KOTA SERANG": "4",
        "KOTA TANGERANG": "4",
        "KAB. PANDEGLANG": "4",
        "KOTA TANGERANG SELATAN": "4"
    },
    "BENGKULU": {
        "KAB. BENGKULU SELATAN": "4",
        "KAB. BENGKULU UTARA": "5",
        "KAB. KAUR": "5",
        "KAB. KEPAHIANG": "5",
        "KAB. LEBONG": "5",
        "KAB. MUKOMUKO": "5",
        "KAB. REJANG LEBONG": "5",
        "KAB. SELUMA": "4",
        "KOTA BENGKULU": "5",
        "KAB. BENGKULU TENGAH": "5"
    },
    "D.I. YOGYAKARTA": {
        "KAB. BANTUL": "5",
        "KAB. GUNUNG KIDUL": "4",
        "KAB. KULON PROGO": "4",
        "KAB. SLEMAN": "4",
        "KOTA YOGYAKARTA": "4"
    },
    "DKI JAKARTA": {
        "KAB. KEPULAUAN SERIBU": "4",
        "KOTA JAKARTA BARAT": "4",
        "KOTA JAKARTA PUSAT": "4",
        "KOTA JAKARTA SELATAN": "4",
        "KOTA JAKARTA TIMUR": "4",
        "KOTA JAKARTA UTARA": "4"
    },
    "GORONTALO": {
        "KAB. BOALEMO": "5",
        "KAB. BONE BOLANGO": "5",
        "KAB. GORONTALO": "5",
        "KAB. GORONTALO UTARA": "5",
        "KAB. POHUWATO": "5",
        "KOTA GORONTALO": "5"
    },
    "JAMBI": {
        "KAB. BATANG HARI": "3",
        "KAB. MUARO JAMBI": "3",
        "KAB. TANJUNG JABUNG BARAT": "3",
        "KAB. TANJUNG JABUNG TIMUR": "3",
        "KOTA JAMBI": "3",
        "KAB. BUNGO": "4",
        "KAB. SAROLANGUN": "4",
        "KAB. TEBO": "3",
        "KAB. MERANGIN": "5",
        "KAB. KERINCI": "5",
        "KOTA SUNGAI PENUH": "5"
    },
    "JAWA BARAT": {
        "KAB. CIREBON": "3",
        "KAB. INDRAMAYU": "4",
        "KAB. SUMEDANG": "5",
        "KOTA CIREBON": "3",
        "KAB. BANDUNG": "4",
        "KAB. BANDUNG BARAT": "4",
        "KAB. BEKASI": "3",
        "KAB. BOGOR": "4",
        "KAB. CIAMIS": "4",
        "KAB. CIANJUR": "4",
        "KAB. GARUT": "4",
        "KAB. KARAWANG": "3",
        "KAB. KUNINGAN": "3",
        "KAB. MAJALENGKA": "3",
        "KAB. PURWAKARTA": "4",
        "KAB. PANGANDARAN": "4",
        "KAB. SUBANG": "5",
        "KAB. SUKABUMI": "4",
        "KAB. TASIKMALAYA": "4",
        "KOTA BANDUNG": "5",
        "KOTA BANJAR": "3",
        "KOTA BEKASI": "4",
        "KOTA BOGOR": "4",
        "KOTA CIMAHI": "5",
        "KOTA DEPOK": "4",
        "KOTA SUKABUMI": "5",
        "KOTA TASIKMALAYA": "3"
    },
    "JAWA TENGAH": {
        "KAB. BANYUMAS": "3",
        "KAB. BATANG": "3",
        "KAB. BLORA": "3",
        "KAB. BOYOLALI": "3",
        "KAB. BREBES": "3",
        "KAB. DEMAK": "4",
        "KAB. GROBOGAN": "4",
        "KAB. JEPARA": "4",
        "KAB. KARANGANYAR": "4",
        "KAB. KENDAL": "3",
        "KAB. KUDUS": "4",
        "KAB. PATI": "4",
        "KAB. PEKALONGAN": "3",
        "KAB. PEMALANG": "3",
        "KAB. PURBALINGGA": "3",
        "KAB. REMBANG": "5",
        "KAB. SEMARANG": "3",
        "KAB. SRAGEN": "3",
        "KAB. TEMANGGUNG": "3",
        "KOTA MAGELANG": "3",
        "KOTA PEKALONGAN": "3",
        "KOTA SALATIGA": "3",
        "KOTA SEMARANG": "3",
        "KOTA SURAKARTA": "4",
        "KOTA TEGAL": "3",
        "KAB. BANJARNEGARA": "3",
        "KAB. CILACAP": "3",
        "KAB. KEBUMEN": "4",
        "KAB. KLATEN": "5",
        "KAB. MAGELANG": "4",
        "KAB. PURWOREJO": "4",
        "KAB. SUKOHARJO": "4",
        "KAB. TEGAL": "4",
        "KAB. WONOGIRI": "4",
        "KAB. WONOSOBO": "3"
    },
    "JAWA TIMUR": {
        "KAB. BANGKALAN": "3",
        "KAB. BOJONEGORO": "3",
        "KAB. BONDOWOSO": "3",
        "KAB. GRESIK": "3",
        "KAB. JEMBER": "4",
        "KAB. JOMBANG": "3",
        "KAB. LAMONGAN": "3",
        "KAB. MADIUN": "3",
        "KAB. MAGETAN": "3",
        "KAB. MOJOKERTO": "3",
        "KAB. NGANJUK": "3",
        "KAB. NGAWI": "3",
        "KAB. PAMEKASAN": "3",
        "KAB. PASURUAN": "3",
        "KAB. PROBOLINGGO": "3",
        "KAB. SAMPANG": "3",
        "KAB. SIDOARJO": "3",
        "KAB. SITUBONDO": "3",
        "KAB. SUMENEP": "3",
        "KAB. TUBAN": "3",
        "KOTA MADIUN": "3",
        "KOTA MOJOKERTO": "3",
        "KOTA PASURUAN": "3",
        "KOTA PROBOLINGGO": "4",
        "KOTA SURABAYA": "3",
        "KAB. BANYUWANGI": "3",
        "KAB. BLITAR": "3",
        "KAB. KEDIRI": "3",
        "KAB. LUMAJANG": "3",
        "KAB. MALANG": "3",
        "KAB. PACITAN": "4",
        "KAB. PONOROGO": "3",
        "KAB. TRENGGALEK": "4",
        "KAB. TULUNGAGUNG": "3",
        "KOTA BATU": "3",
        "KOTA BLITAR": "3",
        "KOTA KEDIRI": "3",
        "KOTA MALANG": "3"
    },
    "KALIMANTAN BARAT": {
        "KAB. BENGKAYANG": "1",
        "KAB. KAPUAS HULU": "1",
        "KAB. KAYONG UTARA": "1",
        "KAB. KETAPANG": "1",
        "KAB. KUBU RAYA": "1",
        "KAB. LANDAK": "1",
        "KAB. MELAWI": "1",
        "KAB. MEMPAWAH": "1",
        "KAB. SAMBAS": "1",
        "KAB. SANGGAU": "1",
        "KAB. SEKADAU": "1",
        "KAB. SINTANG": "1",
        "KOTA PONTIANAK": "1",
        "KOTA SINGKAWANG": "1"
    },
    "KALIMANTAN SELATAN": {
        "KAB. BALANGAN": "1",
        "KAB. BANJAR": "1",
        "KAB. BARITO KUALA": "1",
        "KAB. HULU SUNGAI SELATAN": "1",
        "KAB. HULU SUNGAI TENGAH": "1",
        "KAB. HULU SUNGAI UTARA": "1",
        "KAB. KOTABARU": "1",
        "KAB. TABALONG": "1",
        "KAB. TANAH BUMBU": "1",
        "KAB. TANAH LAUT": "1",
        "KAB. TAPIN": "1",
        "KOTA BANJARBARU": "1",
        "KOTA BANJARMASIN": "1"
    },
    "KALIMANTAN TENGAH": {
        "KAB. BARITO SELATAN": "1",
        "KAB. BARITO TIMUR": "1",
        "KAB. BARITO UTARA": "1",
        "KAB. GUNUNG MAS": "1",
        "KAB. KAPUAS": "1",
        "KAB. KATINGAN": "1",
        "KAB. KOTAWARINGIN BARAT": "1",
        "KAB. KOTAWARINGIN TIMUR": "1",
        "KAB. LAMANDAU": "1",
        "KAB. MURUNG RAYA": "1",
        "KAB. PULANG PISAU": "1",
        "KAB. SERUYAN": "1",
        "KAB. SUKAMARA": "1",
        "KOTA PALANG KARAYA": "1"
    },
    "KALIMANTAN TIMUR": {
        "KAB. KUTAI BARAT": "1",
        "KAB. KUTAI KARTANEGARA": "1",
        "KAB. PASER": "1",
        "KAB. PENAJAM PASER UTARA": "1",
        "KOTA BALIKPAPAN": "1",
        "KOTA SAMARINDA": "1",
        "KAB. KUTAI TIMUR": "1",
        "KOTA BONTANG": "2",
        "KAB. BERAU": "2",
        "KAB. MAHAKAM ULU": "1"
    },
    "KALIMANTAN UTARA": {
        "KAB. MALINAU": "2",
        "KAB. NUNUKAN": "1",
        "KAB. TANA TIDUNG": "1",
        "KOTA TARAKAN": "2",
        "KAB. BULUNGAN": "1"
    },
    "KEPULAUAN BANGKA BELITUNG": {
        "KAB. BANGKA": "3",
        "KAB. BANGKA BARAT": "3",
        "KAB. BANGKA TENGAH": "2",
        "KAB. BELITUNG": "1",
        "KAB. BELITUNG TIMUR": "1",
        "KOTA PANGKAL PINANG": "2",
        "KAB. BANGKA SELATAN": "2"
    },
    "KEPULAUAN RIAU": {
        "KAB. BINTAN": "2",
        "KAB. KARIMUN": "2",
        "KAB. LINGGA": "3",
        "KAB. NATUNA": "1",
        "KOTA BATAM": "2",
        "KOTA TANJUNG PINANG": "2",
        "KAB. KEPULAUAN ANAMBAS": "1"
    },
    "LAMPUNG": {
        "KAB. LAMPUNG TENGAH": "4",
        "KAB. LAMPUNG TIMUR": "4",
        "KAB. LAMPUNG UTARA": "4",
        "KAB. TULANGBAWANG": "4",
        "KAB. WAY KANAN": "4",
        "KOTA METRO": "4",
        "KAB. LAMPUNG SELATAN": "4",
        "KAB. PESAWARAN": "4",
        "KOTA BANDAR LAMPUNG": "4",
        "KAB. LAMPUNG BARAT": "5",
        "KAB. TANGGAMUS": "5",
        "KAB. PESISIR BARAT": "5",
        "KAB. PRINGSEWU": "4",
        "KAB. MESUJI": "3",
        "KAB. TULANG BAWANG BARAT": "4"
    },
    "MALUKU": {
        "KAB. MALUKU TENGAH": "5",
        "KAB. MALUKU TENGGARA": "5",
        "KAB. SERAM BAGIAN BARAT": "5",
        "KOTA TUAL": "5",
        "KAB. BURU": "5",
        "KAB. KEPULAUAN ARU": "4",
        "KAB. MALUKU TENGGARA BARAT": "5",
        "KAB. SERAM BAGIAN TIMUR": "5",
        "KOTA AMBON": "5",
        "KAB. MALUKU BARAT DAYA": "4",
        "KAB. BURU SELATAN": "4"
    },
    "MALUKU UTARA": {
        "KAB. HALMAHERA TENGAH": "4",
        "KAB. HALMAHERA TIMUR": "4",
        "KAB. HALMAHERA BARAT": "5",
        "KAB. HALMAHERA SELATAN": "4",
        "KAB. HALMAHERA UTARA": "5",
        "KAB. KEPULAUAN SULA": "4",
        "KOTA TERNATE": "5",
        "KOTA TIDORE KEPULAUAN": "5",
        "KAB. PULAU TALIABU": "4",
        "KAB. PULAU MOROTAI": "5"
    },
    "NANGGROE ACEH DARUSSALAM": {
        "KAB. ACEH UTARA": "5",
        "KOTA LHOKSEUMAWE": "4",
        "KAB. ACEH TAMIANG": "4",
        "KAB. ACEH TENGAH": "5",
        "KAB. ACEH TIMUR": "5",
        "KAB. BENER MERIAH": "4",
        "KAB. BIREUEN": "5",
        "KOTA LANGSA": "4",
        "KAB. ACEH BARAT": "5",
        "KAB. ACEH BARAT DAYA": "5",
        "KAB. ACEH BESAR": "5",
        "KAB. ACEH JAYA": "5",
        "KAB. ACEH SELATAN": "5",
        "KAB. ACEH SINGKIL": "5",
        "KAB. ACEH TENGGARA": "5",
        "KAB. GAYO LUES": "5",
        "KAB. NAGAN RAYA": "5",
        "KAB. PIDIE": "5",
        "KAB. PIDIE JAYA": "5",
        "KAB. SIMEULUE": "5",
        "KOTA BANDA ACEH": "5",
        "KOTA SABANG": "5",
        "KOTA SUBULUSSALAM": "5"
    },
    "NUSA TENGGARA BARAT": {
        "KAB. BIMA": "3",
        "KAB. LOMBOK TENGAH": "4",
        "KAB. LOMBOK TIMUR": "3",
        "KAB. SUMBAWA": "3",
        "KAB. SUMBAWA BARAT": "3",
        "KOTA BIMA": "4",
        "KAB. DOMPU": "3",
        "KAB. LOMBOK BARAT": "4",
        "KOTA MATARAM": "5",
        "KAB. LOMBOK UTARA": "3"
    },
    "NUSA TENGGARA TIMUR": {
        "KAB. ENDE": "3",
        "KAB. FLORES TIMUR": "3",
        "KAB. KUPANG": "4",
        "KAB. MANGGARAI": "3",
        "KAB. MANGGARAI BARAT": "4",
        "KAB. MANGGARAI TIMUR": "3",
        "KAB. NGADA": "3",
        "KAB. ROTE NDAO": "4",
        "KAB. SIKKA": "3",
        "KAB. SUMBA TIMUR": "3",
        "KOTA KUPANG": "5",
        "KAB. ALOR": "3",
        "KAB. BELU": "4",
        "KAB. LEMBATA": "3",
        "KAB. NAGEKEO": "3",
        "KAB. SUMBA BARAT": "4",
        "KAB. SUMBA BARAT DAYA": "4",
        "KAB. SUMBA TENGAH": "3",
        "KAB. TIMOR TENGAH SELATAN": "3",
        "KAB. TIMOR TENGAH UTARA": "3",
        "KAB. MALAKA": "4",
        "KAB. SABU RAIJUA": "5"
    },
    "PAPUA": {
        "KAB. MERAUKE": "1",
        "KAB. ASMAT": "3",
        "KAB. BOVEN DIGOEL": "2",
        "KAB. MAPPI": "2",
        "KAB. MIMIKA": "5",
        "KAB. PUNCAK JAYA": "3",
        "KAB. BIAK NUMFOR": "4",
        "KAB. PANIAI": "3",
        "KAB. PEGUNUNGAN BINTANG": "5",
        "KAB. SUPIORI": "5",
        "KAB. WAROPEN": "4",
        "KAB. KEPULAUAN YAPEN": "5",
        "KAB. JAYAPURA": "5",
        "KAB. JAYAWIJAYA": "3",
        "KAB. KEEROM": "4",
        "KAB. NABIRE": "5",
        "KAB. SARMI": "5",
        "KAB. TOLIKARA": "3",
        "KAB. YAHUKIMO": "3",
        "KOTA JAYAPURA": "3",
        "KAB. MAMBERAMO RAYA": "4",
        "KAB. NDUGA": "4",
        "KAB. LANNY JAYA": "3",
        "KAB. MAMBERAMO TENGAH": "3",
        "KAB. YALIMO": "3",
        "KAB. PUNCAK": "3",
        "KAB. DOGIYAI": "4",
        "KAB. INTAN JAYA": "3",
        "KAB. DEIYAI": "4"
    },
    "PAPUA BARAT": {
        "KAB. FAKFAK": "4",
        "KAB. KAIMANA": "5",
        "KAB. SORONG SELATAN": "3",
        "KOTA SORONG": "5",
        "KAB. RAJA AMPAT": "3",
        "KAB. SORONG": "4",
        "KAB. TELUK BINTUNI": "3",
        "KAB. TELUK WONDOMA": "3",
        "KAB. MANOKWARI": "4",
        "KAB. MANOKWARI SELATAN": "4",
        "KAB. PEGUNUNGAN ARFAK": "4",
        "KAB. TAMBRAUW": "5",
        "KAB. MAYBRAT": "4"
    },
    "RIAU": {
        "KAB. BENGKALIS": "3",
        "KAB. INDRAGIRI HILIR": "3",
        "KAB. INDRAGIRI HULU": "4",
        "KAB. PELALAWAN": "4",
        "KAB. ROKAN HILIR": "4",
        "KAB. SIAK": "3",
        "KOTA DUMAI": "3",
        "KAB. KAMPAR": "4",
        "KAB. KUANTAN SINGINGI": "4",
        "KAB. ROKAN HULU": "4",
        "KOTA PEKANBARU": "4",
        "KAB. KEPULAUAN MERANTI": "3"
    },
    "SULAWESI SELATAN": {
        "KAB. BARRU": "2",
        "KAB. ENREKANG": "3",
        "KAB. LUWU": "2",
        "KAB. LUWU TIMUR": "4",
        "KAB. LUWU UTARA": "3",
        "KAB. PINRANG": "3",
        "KAB. SIDENRENG RAPPANG": "4",
        "KAB. SOPPENG": "3",
        "KAB. WAJO": "3",
        "KOTA PALOPO": "3",
        "KOTA PARE-PARE": "3",
        "KAB. BANTAENG": "2",
        "KAB. BONE": "2",
        "KAB. BULUKUMBA": "2",
        "KAB. GOWA": "2",
        "KAB. JENEPONTO": "2",
        "KAB. MAROS": "2",
        "KAB. PANGKAJENE DAN KEPULAUAN": "3",
        "KAB. SELAYAR": "4",
        "KAB. SINJAI": "2",
        "KAB. TAKALAR": "2",
        "KOTA MAKASSAR": "2",
        "KAB. TANA TORAJA": "3",
        "KAB. TORAJA UTARA": "3"
    },
    "SULAWESI BARAT": {
        "KAB. MAMUJU UTARA": "4",
        "KAB. MAJENE": "5",
        "KAB. MAMASA": "3",
        "KAB. MAMUJU": "4",
        "KAB. POLEWALI MANDAR": "5",
        "KAB. MAMUJU TENGAH": "4"
    },
    "SULAWESI TENGAH": {
        "KAB. MOROWALI": "4",
        "KAB. BANGGAI KEPULAUAN": "4",
        "KAB. DONGGALA": "4",
        "KAB. POSO": "5",
        "KAB. TOJO UNA-UNA": "4",
        "KOTA PALU": "5",
        "KAB. BANGGAI": "4",
        "KAB. BUOL": "5",
        "KAB. PARIGI MOUTONG": "4",
        "KAB. TOLI-TOLI": "5",
        "KAB. BANGGAI LAUT": "4",
        "KAB. MOROWALI UTARA": "4",
        "KAB. SIGI": "4"
    },
    "SULAWESI TENGGARA": {
        "KAB. BOMBANA": "2",
        "KAB. BUTON": "3",
        "KAB. KOLAKA": "2",
        "KAB. KOLAKA UTARA": "3",
        "KAB. KONAWE": "4",
        "KAB. KONAWE SELATAN": "3",
        "KAB. KONAWE UTARA": "5",
        "KAB. MUNA": "2",
        "KAB. WAKATOBI": "3",
        "KOTA BAU-BAU": "2",
        "KAB. BUTON UTARA": "3",
        "KOTA KENDARI": "5",
        "KAB. KONAWE KEPULAUAN": "4",
        "KAB. KOLAKA TIMUR": "2"
    },
    "SULAWESI UTARA": {
        "KAB. BOLAANG MONGONDOW": "4",
        "KAB. BOLAANG MONGONDOW UTARA": "4",
        "KAB. KEPULAUAN SANGIHE": "5",
        "KAB. SIAU TAGULANDANG BITARO": "5",
        "KAB. KEPULAUAN TALAUD": "5",
        "KAB. MINAHASA": "5",
        "KAB. MINAHASA SELATAN": "4",
        "KAB. MINAHASA TENGGARA": "5",
        "KAB. MINAHASA UTARA": "5",
        "KOTA BITUNG": "5",
        "KOTA KOTAMOBAGU": "4",
        "KOTA MANADO": "4",
        "KOTA TOMOHON": "5",
        "KAB. BOLAANG MONGONDOW SELATAN": "4",
        "KAB. BOLAANG MONGONDOW TIMUR": "4"
    },
    "SUMATERA BARAT": {
        "KAB. DHARMASRAYA": "4",
        "KAB. PASAMAN": "5",
        "KAB. LIMA PULUH KOTA": "5",
        "KAB. PASAMAN BARAT": "5",
        "KAB. SIJUNJUNG": "4",
        "KAB. TANAH DATAR": "5",
        "KOTA PAYAKUMBUH": "4",
        "KOTA SAWAH LUNTO": "5",
        "KAB. AGAM": "5",
        "KAB. KEPULAUAN MENTAWAI": "5",
        "KAB. PADANG PARIAMAN": "5",
        "KAB. PESISIR SELATAN": "5",
        "KAB. SOLOK": "5",
        "KAB. SOLOK SELATAN": "5",
        "KOTA BUKITTINGGI": "5",
        "KOTA PADANG": "5",
        "KOTA PADANG PANJANG": "5",
        "KOTA PARIAMAN": "5",
        "KOTA SOLOK": "5"
    },
    "SUMATERA SELATAN": {
        "KAB. OGAN ILIR": "4",
        "KAB. OGAN KOMERING ILIR": "3",
        "KOTA PALEMBANG": "3",
        "KAB. BANYU ASIN": "4",
        "KAB. LAHAT": "5",
        "KAB. MUARA ENIM": "4",
        "KAB. MUSI BANYUASIN": "4",
        "KAB. OGAN KOMERING ULU": "4",
        "KAB. OGAN KOMERING ULU TIMUR": "4",
        "KOTA PRABUMULIH": "4",
        "KAB. EMPAT LAWANG": "5",
        "KAB. MUSI RAWAS": "4",
        "KAB. OGAN KOMERING ULU SELATAN": "5",
        "KOTA LUBUKLINGGAU": "5",
        "KOTA PAGAR ALAM": "5",
        "KAB. PENUKAL ABAB LEMATANG ILIR": "4",
        "KAB. MUSI RAWAS UTARA": "4"
    },
    "SUMATERA UTARA": {
        "KAB. ASAHAN": "4",
        "KAB. BATU BARA": "4",
        "KAB. DELI SERDANG": "4",
        "KAB. LABUHAN BATU": "4",
        "KAB. LANGKAT": "5",
        "KAB. SERDANG BEDAGAI": "4",
        "KOTA BINJAI": "4",
        "KOTA MEDAN": "4",
        "KOTA TANJUNG BALAI": "4",
        "KOTA TEBING TINGGI": "4",
        "KAB. DAIRI": "5",
        "KAB. KARO": "5",
        "KAB. MANDAILING NATAL": "5",
        "KAB. PADANG LAWAS": "5",
        "KAB. PAKPAK BHARAT": "5",
        "KAB. SAMOSIR": "5",
        "KAB. SIMALUNGUN": "5",
        "KAB. TAPANULI SELATAN": "5",
        "KAB. TOBA SAMOSIR": "5",
        "KOTA PADANGSIDIMPUAN": "5",
        "KOTA PEMATANG SIANTAR": "4",
        "KAB. HUMBANG HASUNDUTAN": "5",
        "KAB. NIAS": "5",
        "KAB. NIAS SELATAN": "5",
        "KAB. TAPANULI TENGAH": "5",
        "KAB. TAPANULI UTARA": "5",
        "KAB. PADANG LAWAS UTARA": "5",
        "KAB. LABUHAN BATU SELATAN": "4",
        "KAB. LABUHAN BATU UTARA": "4",
        "KAB. NIAS UTARA": "5",
        "KAB. NIAS BARAT": "5",
        "KOTA GUNUNGSITOLI": "5",
        "KOTA SIBOLGA": "5"
    }
};